### ISSUE TITLE
Can't seem to run the server

### ISSUE THREAD

**Issue by mtpultz** [IgorMinar/foodme#10]
I get this error when I try and run web-server.bat, and when I read the seed docs it says I should be able to just type 'npm start', but that doesn't work either.  The .bat has the right path, so not sure why this is happening.

Error: Cannot find module 'd:\htdocs\foodme\scripts\server\start.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by robersonfox** [comment]
npm install?
