### ISSUE TITLE
Error: Cannot find module 'open'  when running server 

### ISSUE THREAD

**Issue by ghost** [IgorMinar/foodme#5]
Hi there, 
I am trying to follow the tutorial and when I want to run server I am getting this errors. Any idea how to fix it ? Thank you in advance.

```
marek@Lenovo:~/Documents/Code/angularjs/foodme$ ./scripts/web-server.sh

module.js:340
    throw err;
          ^
Error: Cannot find module 'open'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/marek/Documents/Code/angularjs/foodme/server/index.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by lukevenediger** [comment]
I got past that by installing the 'open' module:

```
$ sudo npm install -g open
```

**Comment by kapilkd** [comment]
First run below command 

npm install open

then try to run your command

**Comment by murilobjj** [comment]
$ node server.js
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'C:\Users\Murilo\Desktop\node-ipa\server.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,

**Comment by murilobjj** [comment]
continuo com o mesmo erro

**Comment by yashmanuraj2** [comment]
@murilobjj getting the same error  while running my app
